[package]
name = "abs_mm"
version = "0.1.1"
edition = "2021"

authors = ["lino <lino_snsalias@outlook.com>"]
description = "Abstract Memory Management"
repository = "https://github.com/ljsnogard/abs_mm"
keywords = ["traits", "smart-pointer"]
categories = ["no-std", "memory-management"]
license = "MIT/Apache-2.0"
readme = "README.md"

[features]
std_smart_pointers = ["arc", "box", "rc"]
arc = ["std", "global_alloc"]
box = ["std", "global_alloc"]
rc = ["std", "global_alloc"]
global_alloc = []
std = []
default = []

[dev-dependencies]
log = { version = "0.4.*" }
env_logger = { version = "0.11.*" }
